version: '3.8'

services:
  db:
    image: mysql
    container_name: mysql_db
    restart: always
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: test
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: root 
      MYSQL_PASSWORD: test
    volumes:
      - mysql_data:/var/lib/mysql
      - /exo_person/bdd_person.sql:/docker-entrypoint-initdb.d/bdd_person.sql
    networks:
      - test-network

  build-todo-spring:
    build:
      context: ./exo_person
      dockerfile: dockerfile
    ports:
      - "8080:8080" 
    networks:
      - test-network


  build-todo-react:
    build:
      context: ./exo_person_react
      dockerfile: dockerfile
    ports:
      - "9090:3000" 

networks: 
  test-network:
    driver: bridge

volumes:
  mysql_data: